services:
  terrapeak:
    image: aliharirian/terrapeak:latest
    container_name: terrapeak
    ports:
      - "8081:8081"
    volumes:
      - ./cfg.yml:/app/cfg.yml:ro
      - terrapeak-data:/data
    environment:
      - LOG_LEVEL=info
    networks:
      - terrapeak-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8081/healthz"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped
    depends_on:
      minio:
        condition: service_healthy

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    restart: unless-stopped
    networks:
      - terrapeak-network
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  terrapeak-network:
    name: terrapeak-network
    driver: bridge

volumes:
  minio-data:
    name: minio-data
    driver: local
  terrapeak-data:
    name: terrapeak-data
    driver: local
