version: "3.9"

services:
  TerraPeak:
    build:
      context: .
      dockerfile: registry/Dockerfile
    image: aliharirian/TerraPeak:latest
    container_name: TerraPeak
    ports:
      - "8081:8081"
    volumes:
      - ./cfg.yml:/app/cfg.yml:ro
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8081/healthz"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped

  MinIO:
    image: minio/minio:latest
    container_name: MinIO
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    restart: unless-stopped
    networks:
      - terrapeak-network
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  terrapeak-network:
    driver: bridge

volumes:
  minio-data:
    driver: local
