name: Release & Publish

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

env:
  DOCKER_IMAGE: aliharirian/terrapeak

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Download dependencies
        run: |
          cd registry
          go mod download
          go mod verify

      - name: Run tests
        run: |
          cd registry
          go test -v -race ./...

  semver:
    name: Determine Version (semantic-release)
    runs-on: ubuntu-latest
    needs: [test]
    outputs:
      tag: ${{ steps.after.outputs.tag }}
      version: ${{ steps.after.outputs.version }}
      no_new_release: ${{ steps.decide.outputs.no_new_release }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # semantic-release needs full history

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install semantic-release
        run: |
          npm -g i \
            semantic-release \
            @semantic-release/changelog \
            @semantic-release/git \
            @semantic-release/github \
            conventional-changelog-conventionalcommits \
            @semantic-release/commit-analyzer \
            @semantic-release/release-notes-generator

      - name: Previous tag (before)
        id: before
        run: |
          git fetch --tags --force || true
          PREV=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          echo "prev=${PREV}" >> $GITHUB_OUTPUT
          echo "Previous tag: ${PREV}"

      - name: Run semantic-release
        id: semrel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release --no-ci

      - name: Latest tag (after)
        id: after
        run: |
          git fetch --tags --force
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          echo "version=${TAG#v}" >> $GITHUB_OUTPUT
          echo "Latest tag: ${TAG}; version: ${TAG#v}"

      - name: Decide if a new release was created
        id: decide
        run: |
          if [ "${{ steps.before.outputs.prev }}" = "${{ steps.after.outputs.tag }}" ] || [ -z "${{ steps.after.outputs.tag }}" ]; then
            echo "no_new_release=true" >> $GITHUB_OUTPUT
            echo "No new release created."
          else
            echo "no_new_release=false" >> $GITHUB_OUTPUT
            echo "New release: ${{ steps.after.outputs.tag }}"
          fi

  docker:
    name: Build & Push Docker (latest + version tags)
    needs: semver
    if: ${{ needs.semver.outputs.no_new_release == 'false' && needs.semver.outputs.tag != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push (linux/amd64, linux/arm64)
        uses: docker/build-push-action@v6
        with:
          context: registry
          file: registry/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            VERSION=${{ needs.semver.outputs.version }}
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ needs.semver.outputs.version }}
            ${{ env.DOCKER_IMAGE }}:${{ needs.semver.outputs.tag }}

  binaries:
    name: Build & Upload Binaries (Linux/macOS)
    needs: semver
    if: ${{ needs.semver.outputs.no_new_release == 'false' && needs.semver.outputs.tag != '' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Build
        env:
          CGO_ENABLED: 0
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          VERSION: ${{ needs.semver.outputs.version }}
        run: |
          mkdir -p dist
          BIN_NAME=terrapeak_${GOOS}_${GOARCH}
          if [ "${GOOS}" = "windows" ]; then BIN_NAME="${BIN_NAME}.exe"; fi
          cd registry
          go build -trimpath -ldflags "-s -w -X main.version=${VERSION}" -o "../dist/${BIN_NAME}" .

      - name: Upload binaries to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.semver.outputs.tag }}
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
